name: CraftingRestriction
main: terranetworkorg.CraftingRestriction.CraftingRestriction
version: 1.2.1
author: TerraNetworkOrg
depend: [Spout,Vault]
commands:
  craftingrestriction:
    description: Lists plugin details
    usage: /<command>
    aliases: [cr,crestrict]